name: CI Workflow  # Tên workflow

on:                # Sự kiện kích hoạt workflow
  push:            # Kích hoạt khi có lệnh push vào repository
    branches:      
      - master      # Chỉ áp dụng với nhánh "main"
  pull_request:   # Kích hoạt khi có pull request

jobs:
  build:
    runs-on: ubuntu-latest # Loại runner để chạy job (Ubuntu, Windows, macOS)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Lẫy mã nguồn về
      - name: Setup Node.js 
        uses: actions/setup-node@v3  # Cài đặt Node.js
        with:
          node-version: 14
      - uses: npm install -D esbuild  # tool để build sang JS phiên bản cũ hơn + tối ưu hiệu suất
      
      - uses: npm run build
      
      - name: Set up QEMU  # Quick Emulator giúp giả lập các kiến trúc phần cứng khác nhau
        uses: docker/setup-qemu-action@v1  # --> QEMU giúp hỗ trợ build và chạy container trên các kiến trúc phần cứng khác nhau
      
      - names: Set up Docker Buildx # Thiết lập Docker Buildx, một tiện ích mở rộng của Docker để build hình ảnh container một cách linh hoạt.
        uses: docker/setup-buildx-action@v2  # VD: build image cho nhiều kiến trúc khác nhau 1 lúc
      
      - names: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - names: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dongnv4724/learn_cicd:staging



        